### ISSUE TITLE
Using EFS for persistent storage 

### ISSUE THREAD

**Issue by aupadh12** [openanalytics/shinyproxy-jupyter-notebook-demo#1]
Hi Team,

IS it possible to use EFS as persistent storage for shinyproxy running on EKS? We need this in order to allow collaboration between multiple users.

**Comment by LEDfan** [comment]
Hi @aupadh12 

If I'm not mistaken, you were already able to use EFS in the meantime. For other readers, it's indeed possible to use EFS for persistence storage. There are two steps required to set it up (in k8s):
 - setup EFS in your k8s cluster: https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html
 - mount the volume using `kubernetes-pod-patches` (see: ) and specify the correct StorageClass for EFS. https://shinyproxy.io/documentation/configuration/#apps
