### ISSUE TITLE
dash app developed in jupyter

### ISSUE THREAD

**Issue by BiernatPiotr** [openanalytics/shinyproxy-jupyter-notebook-demo#3]
Hi,

do you have any idea, how to preview dash app developed in jupyter notebook in shinyproxy? When I try to run app from notebook I have no idea how to access it.

`app.run_server(mode='external', host="127.0.0.1", port=8049)`
`Dash app running on http://127.0.0.1:8049/`

When I run a shiny app in RStudio in shinyproxy and try to preview it there is info about address where app is running from R like:
`Listening on http://127.0.0.1:6331`

And new tab apperas with some specific addres like:
https://mydomain.com/app_direct_i/rstudio/_/p/ccae08ce/

Is there any way to get such an address for dash app?

**Comment by LEDfan** [comment]
Sorry, I missed this issue. 
Continuing in https://github.com/openanalytics/shinyproxy/issues/359
